import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { Toaster } from 'react-hot-toast';
import { AuthContextProvider } from "./Context/AuthContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthContextProvider>
        <div>
        <Navbar />
        <div className="w-full min-h-[75vh]">{children}</div>
        <Footer />
        <Toaster />
        </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
